#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

# BIFSD
obj-$(CONFIG_X2_BIFSD)			+= x2_bifsd.o
obj-$(CONFIG_X2_BIFSD)			+= x2_bifsd_isr.o
