obj-${CONFIG_CLK_X2}		+= fixed-clk.o
obj-${CONFIG_CLK_X2}		+= laintpll.o
obj-${CONFIG_CLK_X2}		+= fracpll.o
obj-${CONFIG_CLK_X2}		+= mux.o
obj-${CONFIG_CLK_X2}		+= divider.o
obj-${CONFIG_CLK_X2}		+= gate.o
obj-${CONFIG_CLK_X2}		+= fixed-factor.o
