#
# (C) Copyright 2014 - 2015 Xilinx, Inc.
# Michal Simek <michal.simek@xilinx.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_SPL_BUILD) += spl.o x2_utils.o dw_mmc_spl.o x2_mmc_spl.o x2_ap_spl.o

obj-y += reset.o

