# SPDX-License-Identifier: GPL-2.0+
#
# Copyright (c) 2013 Samsung Electronics Co., Ltd.
# 	http://www.samsung.com
obj-y += x3_pka.o
obj-y += x3_pka_test.o
obj-y += x3_spacc.o
obj-y += x3_spacc_test.o
