# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2000-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
obj-${CONFIG_VIDEO_HOBOT_XJ3} += hobot_iar.o ../videomodes.o
obj-${CONFIG_VIDEO_HOBOT_XJ3} += hobot_xj3_hdmi_lt8618.o